# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate k nearest neighbors
#' 
#' @param nrow Number of rows
#' @param ncol Number of columns
#' @param f Features matrix
#'
#' @export
knn <- function(nrow, ncol, f) {
    .Call(`_BMDK_knn`, nrow, ncol, f)
}

